# Generated by Django 5.2.11 on 2026-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionrecord",
            name="model_version",
            field=models.CharField(default="logreg_v1", max_length=50),
        ),
        migrations.AlterField(
            model_name="predictionrecord",
            name="risk_band",
            field=models.CharField(
                choices=[
                    ("very_low", "Very low"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("very_high", "Very high"),
                ],
                max_length=20,
            ),
        ),
    ]
